### ISSUE TITLE
Improve layout of cards

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Emoji-Card-Game#1]
Currently cards are laid out in rows of 2. This takes up a lot of vertical space while leaving out a lot of horizontal space. This looks very weird on a standard PC / laptop screen. Experiment with a different number of cards per row, and see what looks best.

Make sure to add screenshots for both before (the current messed up layout) and after (your fixed layout) in your PR. 

UI changes are much easier for PR reviewers when the contributor adds screenshots / gifs, as appropriate, which show the change at a cursory glance, so make this a habit!

**Comment by Vikrantpalle** [comment]
Ma'am I am interested in taking this task up.

**Comment by TsarPrince** [comment]
Ma'am I would like to work on this, please assign it to me.

**Comment by N-Shar-ma** [comment]
@TsarPrince Go ahead!

**Comment by KarthikS373** [comment]
Ma'am can I take this one?

**Comment by N-Shar-ma** [comment]
@KarthikS373 Yes you may!

**Comment by palashb01** [comment]
ma'am, can I take this one?

**Comment by Perumallpardhiv** [comment]
ma'am can you plz assign me this issue...

**Comment by N-Shar-ma** [comment]
@palashb01 @Perumallpardhiv Sorry, there are already 3 successful PRs for this issue, try some other free issues!
