### ISSUE TITLE
Ask player for confirmation before showing hint

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Emoji-Card-Game#2]
Isn't it annoying when an accidental click makes you trigger a hint you didn't need, and hence spoil what could have been a perfect score? Well, you can easily fix this annoyance!

If the player hasn't seen the hint for a certain card before, make sure to ask him/her for `confirm`ation before actually flipping the card to reveal the hint. If he turns down the offer, do not flip the card and do not increment the hint counter.

Hint: This fix only needs an extra condition inside an if condition!

Don't forget to attach a gif showing the confirmation being shown on clicking a card for the first time to your PR, and what happens if the player agrees or denies.

Visual changes are much easier for PR reviewers when the contributor adds screenshots / gifs, as appropriate, which show the change at a cursory glance, so make this a habit!

**Comment by Vikrantpalle** [comment]
Ma'am I am interested in taking this task up.

**Comment by N-Shar-ma** [comment]
@Vikrantpalle go ahead! You have 3 hours from right now

**Comment by ghost** [comment]
Can I also get assigned this issue?

**Comment by N-Shar-ma** [comment]
@delClg Sure, consider yourself assigned and make a PR within 3 hours from now

**Comment by KarthikS373** [comment]
Ma'am can I take this issue up

**Comment by N-Shar-ma** [comment]
> Ma'am can I take this issue up

Yes, go ahead

**Comment by TsarPrince** [comment]
Ma'am I would like to work on it. Can i get it assigned?

**Comment by N-Shar-ma** [comment]
@TsarPrince Though there already 3 PRs for this, since @KarthikS373 's is not quite right, if you make a correct PR before he does, you'll get the score. Make a PR soon!

**Comment by KarthikS373** [comment]
Ma'am I fixed the issue 
sending PR rn

**Comment by KarthikS373** [comment]
@N-Shar-ma @TsarPrince Ma'am fixed the logic issue and edited the same PR please check and confirm

Fix : now the confirm is triggered only once per card
![git](https://user-images.githubusercontent.com/96634646/157869479-f496b8a6-c2ec-4701-94d8-f3cc8e700b09.gif)

**Comment by N-Shar-ma** [comment]
@TsarPrince Sorry we have 3 successful PRs now. Look forward to see your PRs fixing other issues!
