### ISSUE TITLE
Add a new achievement state

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Emoji-Card-Game#3]
Currently the game only acknowledges when you play an absolutely perfect game. Isn't that a little harsh? Luckily you can easily add an achievement state for a "near perfect" game!

If the player has got a full score OR taken 0 hints, show him/her a special message saying "You played a NEAR PERFECT GAME!"

Hint: Look at the code and study how the "PERFECT GAME" achievement is handled for reference

Do add a gif/video showing the message for a "NEAR PERFECT GAME" along with the end stats.

Visual changes are much easier for PR reviewers when the contributor adds screenshots / gifs, as appropriate, which show the change at a cursory glance, so make this a habit!

**Comment by ghost** [comment]
Can I be assigned this issue?

https://user-images.githubusercontent.com/96474794/157795406-f1aea4a6-982f-4961-a221-dfa534b59ca4.mp4

**Comment by N-Shar-ma** [comment]
@delClg The video looks good! Make sure to attach it to your PR as well

**Comment by Vikrantpalle** [comment]
Ma'am I am interested in taking this task up.

**Comment by superiorsd10** [comment]
@N-Shar-ma Ma'am, I think I acquire enough knowledge to resolve this issue, so please consider assigning it to me!

**Comment by N-Shar-ma** [comment]
@superiorsd10 Go ahead!
